export const synonymMap = {
  vids: ["video"],
  vid: ["video"],
  videos: ["video"],
  clip: ["video"],
  clips: ["video"],
  reel: ["short", "video"],
  reels: ["short", "video"],
  shorts: ["short", "video"],
  yt: ["youtube"],
  tutorial: ["tutorial", "guide", "howto"],
  tut: ["tutorial"],
  tuts: ["tutorial"],
  vlog: ["vlog", "blog"],
  stream: ["livestream"],
  streams: ["livestream"],
  live: ["livestream"],
  walkthrough: ["tutorial", "gameplay"],
  episode: ["episode"],
  ep: ["episode"],
  highlight: ["clip", "moment"],
  highlights: ["clip", "moment"],
  bts: ["behind the scenes"],
  howto: ["tutorial", "guide"],
  hacks: ["tips", "tricks"],
  hack: ["tips", "tricks"],
  gameplay: ["game"],
  playthrough: ["game"],
  meme: ["meme"],
  memes: ["meme"],
  parody: ["parody"],
  remix: ["remix"],
  mv: ["music video"],
  cover: ["song", "performance"],
  collab: ["collaboration"],
  collabs: ["collaboration"],
  influencer: ["creator"],
  creator: ["creator"],
  review: ["review"],
  unboxing: ["review"],
  setup: ["tutorial", "install"],
  demo: ["preview"],
  tips: ["guide"],
  tricks: ["guide"],
  comparison: ["review"],
  vs: ["review"],
  workout: ["exercise"],
  workouts: ["exercise"],
  routine: ["program"],
  diet: ["health"],
  insta: ["instagram"],
  ig: ["instagram"],
  fb: ["facebook"],
  tiktok: ["short video"],
  reels: ["short video"],
  snap: ["snapchat"],
};
